# Generated by Django 3.1.2 on 2020-12-03 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_restaurants_auth', '0002_auto_20201203_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('owner_restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_restaurants_auth.restaurant')),
            ],
        ),
    ]
