# Generated by Django 3.1.2 on 2020-12-04 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_restaurants_auth', '0003_restaurant_name'),
        ('app_menu_orders', '0003_auto_20201203_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('phone', models.TextField()),
                ('notes', models.TextField()),
                ('type', models.TextField()),
                ('date_created', models.DateField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_restaurants_auth.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('notes', models.TextField()),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_menu_orders.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_menu_orders.order')),
            ],
        ),
    ]
