# Generated by Django 3.1.2 on 2020-12-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_menu_orders', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(max_length=120),
        ),
    ]
