# Generated by Django 3.1.2 on 2020-12-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_menu_orders', '0005_auto_20201203_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('DEL', 'delivery'), ('TAK', 'takeout'), ('DIN', 'dine-in')], default='TAK', max_length=3),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
