# Generated by Django 3.1.2 on 2020-12-04 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_menu_orders', '0007_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
