# Generated by Django 3.1.2 on 2020-12-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_menu_orders', '0008_auto_20201203_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('STA', 'started'), ('REC', 'recieved'), ('INP', 'in progress'), ('FUL', 'fulfilled')], max_length=3, null=True),
        ),
    ]
