# Generated by Django 3.1.2 on 2020-12-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_menu_orders', '0009_auto_20201204_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='bobert', max_length=120),
            preserve_default=False,
        ),
    ]
