# Generated by Django 3.1.2 on 2020-12-20 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_restaurants_auth', '0005_auto_20201205_1858'),
        ('app_menu_orders', '0010_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='owner_restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_restaurants_auth.restaurant'),
            preserve_default=False,
        ),
    ]
