# Generated by Django 3.1.2 on 2020-12-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_restaurants_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='operating_hours',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
