# Generated by Django 3.1.2 on 2020-12-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_restaurants_auth', '0003_restaurant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='email',
            field=models.CharField(default='alfa.budiman@outlook.com', max_length=120),
            preserve_default=False,
        ),
    ]
