# Generated by Django 3.1.2 on 2020-12-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_restaurants_auth', '0004_restaurant_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='address',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='description',
            new_name='hours',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='country',
            field=models.CharField(default='test', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='public_email',
            field=models.CharField(default='test', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='public_phonenumber',
            field=models.CharField(default='test', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='state_province',
            field=models.CharField(default='test', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='street_address',
            field=models.CharField(default='test', max_length=120),
            preserve_default=False,
        ),
    ]
